### PR TITLE
Kopernicus required fixes, reverting changes between v1.2.6 -> v1.2.7…

### LINKED ISSUE #459: Landing Gear Clipping Through Terrain, Vessel Slides Across Surface, Wheels do not work
Issue is indiscriminate and affects many planetary bodies from different planet packs by different authors. Vessel slides on the slightest slope and is not an issue with the brakes. The motors on wheels run, but the vessel does not move nor steer from it. It happens on all stock/modded gear and wheels. I have found no ways to alleviate this, new save, fresh reinstall, stripped down gamedata to Kopernicus and planet packs only to no effect. I am on Win x64 and currently on 1.9.1-7. It happens on both 1.8.1-1 and 1.10.1 bleeding edge I can confirm.

Let me know If you need any more information, I can easily reproduce this 100% of the time.

A video of a more extreme scenario: https://www.youtube.com/watch?v=KOVDijVEDf8&feature=youtu.be
unknown

### PR DESCRIPTION
**Pull request by R-T-B**
This isn't really a serious pull request, but I think you need to look this over.

This is a branch of MFI Koperncius is presently shipping, which fixes [this bug on Kopernicus project](https://github.com/Kopernicus/Kopernicus/issues/459)

It's really just a recompile of 1.2.6.  I am hoping you can tell us why this seemingly fixes it, and maybe understand the problem better?  We certainly would rather not maintain a separate fork if not needed.

### CODE REVIEW

**Comment by sarbian** [comment]
I guess the problem is some tricky timing with the wheel getting some info before MFI is properly setup. Hard to track down.

I built a version that changes how MFI runs and it may help. Could you test with this one? I will have more time to look into it after xmass.
https://www.sarbian.com/sarbian/ModularFlightIntegrator.dll

**Comment by R-T-B** [comment]
I will distribute to my testers and get feedback.

**Comment by R-T-B** [comment]
Testers report that did "nearly nothing" vs the old MFI (maybe even worse?).  We still are using a recompile of 1.2.6 for now, do be advised.

**Comment by sarbian** [comment]
Can one of your tester provide me a save that shows the problem and do not require 5 mods packs? I tried the save in the Kopernicus bug but I could not really dup the issue and it requires way to much load time to allow me to debug MFI anyway.

**Comment by R-T-B** [comment]
I'll see what I can put together for you.  The mod pack that best reproduces it is closed distribution atm but I am sure I can get permission.

I have trouble reliably duping the issue outside of interstellar packs like this too, so it's probably easiest to just grab the problem mod.

**Comment by pckbls** [comment]
Hi there,

I've also encountered the bug described in the linked issue here. Here's what you need to reproduce the bug:
* KSP 1.10.1
* **The Making History Expansion!!!**
* [KopernicusBE_1101_Release58](https://github.com/R-T-B/Kopernicus/releases/tag/UBE-release-58)
* [Beyond.Home.1.5.2](https://forum.kerbalspaceprogram.com/index.php?/topic/182708-191-110x-beyond-home-150-supports-parallax/)
* [Parallax.1.0.1](https://github.com/Gameslinx/Tessellation/releases/download/1.0.1/Parallax.1.0.1.zip)

Create a simple Vessel (e.g. Mk3 command pod, a fuel tank, some engine, LT-2 landing legs) and attempt to land it anywhere on "Voss". Alternatively I have attached two Sandbox mode save games: [default.zip](https://github.com/sarbian/ModularFlightIntegrator/files/5765953/default.zip)
1. Said vessel in LO around Voss
2. Said vessel landed on Voss standing on its Vector engine with the landing legs glitching through the surface.

You will encounter weird behavior as shown in the small YouTube video that I have put together: https://www.youtube.com/watch?v=LpXp4PQk6Kc

**As soon as you uninstall the Making History Expansion, the issue is gone. 🤷** 

Kind regards
Patrick

**Comment by R-T-B** [comment]
Thanks for this @pckbls, it looks more and more like MFI may not be to blame afterall.

Weird.  I got reports my fork fixed it but suddenly I can't seem to find confirmation of that anywhere.  I will wait a day or two for proof and then probably pull my fork.  This sadly sounds like a squad issue.

**Comment by sarbian** [comment]
I will have a look when I find some free time. The Making History detail is interesting.

**Comment by R-T-B** [comment]
https://github.com/Kopernicus/Kopernicus/issues/459

You may want to read through that as well.  It seems subdivision count is related somehow?

**Comment by R-T-B** [comment]
We are unforking, so this issue is now invalid.  The bug has been determined to not be related to ModularFlightIntegrator, and the fork we made was only able to influence the bug, not fix it.

**Pull request closed without merging**
